import Foundation

/// All bundled default strategy cards defined as Swift code.
///
/// Using Swift literals (rather than a JSON resource file) guarantees the seed
/// always decodes correctly against the current model — no schema drift.
public enum SeedCardProvider {

    public static func makeLibrary() -> KnowledgeLibrary {
        let deck = KnowledgeDeck(
            id: softwareEngineeringDeckID,
            name: "Software Engineering",
            description: "Programming and algorithmic problem-solving techniques.",
            iconName: "square.stack.3d.up",
            displayOrder: 0
        )
        let suits: [CardSuit] = [
            CardSuit(id: "search",         deckID: softwareEngineeringDeckID, name: "Search",         iconName: "magnifyingglass",             displayOrder: 0),
            CardSuit(id: "transformation", deckID: softwareEngineeringDeckID, name: "Transformation", iconName: "arrow.triangle.2.circlepath", displayOrder: 1),
            CardSuit(id: "structure",      deckID: softwareEngineeringDeckID, name: "Structure",      iconName: "square.grid.2x2",             displayOrder: 2),
            CardSuit(id: "state",          deckID: softwareEngineeringDeckID, name: "State",          iconName: "circle.hexagongrid",          displayOrder: 3),
            CardSuit(id: "reliability",    deckID: softwareEngineeringDeckID, name: "Reliability",    iconName: "shield.lefthalf.filled",      displayOrder: 4),
            CardSuit(id: "debugging",      deckID: softwareEngineeringDeckID, name: "Debugging",      iconName: "ladybug",                     displayOrder: 5)
        ]
        return KnowledgeLibrary(decks: [deck], suits: suits, cards: allCards(), relationships: [], sequences: [])
    }

    // MARK: - All cards

    private static func allCards() -> [KnowledgeCard] {
        searchCards() + transformationCards() + structureCards()
            + stateCards() + reliabilityCards() + debuggingCards()
    }

    private static let softwareEngineeringDeckID = "software-engineering"

    /// Builds a `KnowledgeCard` from the same parameter shape the old
    /// `StrategyCard` literals use, so the 46 existing card definitions
    /// below only need `StrategyCard(` renamed to `card(`, not rewritten.
    /// `iconName` is accepted but unused — no view ever read `card.iconName`
    /// (verified via grep), and `KnowledgeCard` has no such field; it's kept
    /// here purely so none of the 46 call sites need editing.
    private static func card(
        name: String,
        suite: String,
        iconName: String = "square.stack.3d.up",
        tags: [String] = [],
        trigger: String = "",
        problemShape: String = "",
        desiredResult: String = "",
        mechanism: String = "",
        requirements: [String] = [],
        advantages: [String] = [],
        costs: [String] = [],
        failureModes: [String] = [],
        timeComplexity: String = "",
        spaceComplexity: String = "",
        flowDescription: String = "",
        codeExample: String = "",
        realWorldExample: String = ""
    ) -> KnowledgeCard {
        KnowledgeCard(
            deckIDs: [softwareEngineeringDeckID],
            suitIDs: [suite],
            kind: .action,
            metadata: .softwareStrategy(SoftwareStrategyFields(
                trigger: trigger,
                problemShape: problemShape,
                desiredResult: desiredResult,
                mechanism: mechanism,
                requirements: requirements,
                advantages: advantages,
                costs: costs,
                failureModes: failureModes,
                timeComplexity: timeComplexity,
                spaceComplexity: spaceComplexity,
                flowDescription: flowDescription,
                codeExample: codeExample,
                realWorldExample: realWorldExample
            )),
            title: name,
            tags: tags
        )
    }

    // MARK: Search

    private static func searchCards() -> [KnowledgeCard] {
        [
            card(
                name: "Linear Scan",
                suite: "search",
                iconName: "arrow.right.to.line",
                tags: ["iteration", "unsorted", "simple"],
                trigger: "Need to find one item in an unsorted or small collection.",
                problemShape: "Collection is unsorted; no index or hash structure is available.",
                desiredResult: "Return the first matching element or nil if absent.",
                mechanism: "Iterate every element in sequence, testing the predicate at each step.",
                requirements: ["Iterable collection"],
                advantages: ["No preprocessing; works on any collection", "Simple to reason about and audit"],
                costs: ["O(n) per query; degrades on large collections with frequent queries"],
                failureModes: ["Slow when applied repeatedly to a large, stable dataset where hashing would be better"],
                timeComplexity: "O(n)",
                spaceComplexity: "O(1)",
                flowDescription: "For each element: if predicate matches, return it. Return nil after full pass.",
                codeExample: "let match = items.first { $0.id == targetID }",
                realWorldExample: "Finding a config entry in a small, rarely-searched list of overrides."
            ),
            card(
                name: "Exhaustive Pairwise Comparison",
                suite: "search",
                iconName: "arrow.triangle.swap",
                tags: ["pairs", "brute-force", "comparison"],
                trigger: "Need to compare every pair of elements to find matches, conflicts, or distances.",
                problemShape: "No structure to exploit; all pairs must be evaluated.",
                desiredResult: "All pairs satisfying a relation, or the best pair by some metric.",
                mechanism: "Nested iteration: outer loop over i, inner loop over j where j > i.",
                requirements: ["Indexable collection"],
                advantages: ["Correct for any comparison relation", "No setup cost"],
                costs: ["O(n²) time; infeasible for n > ~10,000 in latency-sensitive paths"],
                failureModes: ["Implicit assumption that order doesn't matter when it does"],
                timeComplexity: "O(n²)",
                spaceComplexity: "O(1) comparison; O(pairs) if collecting results",
                flowDescription: "For i in 0..<n: for j in (i+1)..<n: check pair (i, j).",
                codeExample: "for i in 0..<items.count { for j in (i+1)..<items.count { compare(items[i], items[j]) } }",
                realWorldExample: "Detecting duplicate invoice numbers in a batch of 200 records."
            ),
            card(
                name: "Hash-Based Lookup",
                suite: "search",
                iconName: "number.square",
                tags: ["hash", "dictionary", "membership", "fast-lookup"],
                trigger: "Repeatedly checking whether values or keys already exist.",
                problemShape: "Membership or key-value lookup repeated many times over a stable set.",
                desiredResult: "O(1) expected lookup after one-time O(n) build.",
                mechanism: "Insert all keys into a hash map. Each subsequent lookup is O(1) expected.",
                requirements: ["Hashable keys", "Enough memory for the table"],
                advantages: ["O(1) average lookup", "Eliminates redundant scans"],
                costs: ["O(n) extra memory", "Hash collisions degrade to O(n) worst case"],
                failureModes: ["Poor hash distribution; key type mutated after insertion; initial build cost amortized over too few queries"],
                timeComplexity: "O(1) avg / O(n) worst per lookup",
                spaceComplexity: "O(n)",
                flowDescription: "Build: insert each element. Query: compute hash, probe bucket, return result.",
                codeExample: "let lookup = Dictionary(uniqueKeysWithValues: items.map { ($0.id, $0) })\nlet found = lookup[targetID]",
                realWorldExample: "Checking whether a transaction ID was already processed in a reconciliation run."
            ),
            card(
                name: "Frequency Counting",
                suite: "search",
                iconName: "chart.bar",
                tags: ["count", "histogram", "grouping"],
                trigger: "Need to know how often each distinct value appears.",
                problemShape: "Aggregating occurrences across a collection in a single pass.",
                desiredResult: "A map from value to count (or top-k most common values).",
                mechanism: "Hash map of value → count. Increment on each occurrence.",
                requirements: ["Hashable values"],
                advantages: ["Single O(n) pass", "Naturally reveals modes and outliers"],
                costs: ["O(k) memory where k is the number of distinct values", "High cardinality can cause memory pressure"],
                failureModes: ["Float equality issues as keys; unbounded cardinality causing OOM"],
                timeComplexity: "O(n)",
                spaceComplexity: "O(k) distinct values",
                flowDescription: "For each element: counts[element, default: 0] += 1. Return counts.",
                codeExample: "var freq: [String: Int] = [:]\nfor item in items { freq[item, default: 0] += 1 }",
                realWorldExample: "Counting how many invoices hit each vendor code to detect abnormal volume."
            ),
            card(
                name: "Sort and Scan",
                suite: "search",
                iconName: "arrow.up.arrow.down",
                tags: ["sort", "adjacency", "duplicates"],
                trigger: "Sorting the data would make the target obvious (adjacent elements, ranges, duplicates).",
                problemShape: "Pattern is structural (duplicates, gaps, ordering violations) and invisible in unsorted data.",
                desiredResult: "Find the pattern by scanning sorted output.",
                mechanism: "Sort the collection, then do a single linear scan to detect the pattern.",
                requirements: ["Comparable elements", "Mutating the order is acceptable"],
                advantages: ["Simple post-sort scan logic", "Reveals adjacency-based patterns cheaply"],
                costs: ["O(n log n) upfront sort", "Destroys original order unless a copy is made"],
                failureModes: ["Sort stability matters but is ignored; pattern is non-adjacent even when sorted"],
                timeComplexity: "O(n log n)",
                spaceComplexity: "O(1) in-place or O(n) copy",
                flowDescription: "Sort → scan adjacent pairs or windows for the pattern.",
                codeExample: "let sorted = items.sorted()\nfor i in 1..<sorted.count where sorted[i] == sorted[i-1] { /* duplicate */ }",
                realWorldExample: "Finding duplicate line items in a sorted expense report."
            ),
            card(
                name: "Two Pointers",
                suite: "search",
                iconName: "arrow.left.and.right",
                tags: ["sorted", "pair", "convergence"],
                trigger: "Find pairs or subarrays in a sorted collection satisfying a constraint.",
                problemShape: "Sorted array; need pairs summing to target, or a range meeting a condition.",
                desiredResult: "All qualifying pairs or the optimal subarray in O(n) after the sort.",
                mechanism: "Place one pointer at start, one at end. Move them toward each other based on comparison.",
                requirements: ["Sorted input", "Problem has a monotonic property exploitable by pointer movement"],
                advantages: ["O(n) scan of sorted input vs. O(n²) brute force"],
                costs: ["Requires sorted input (O(n log n) upfront if not already sorted)", "Logic for duplicates must be explicit"],
                failureModes: ["Wrong pointer movement direction; not handling duplicate values correctly"],
                timeComplexity: "O(n) after sort",
                spaceComplexity: "O(1)",
                flowDescription: "left = 0, right = n-1. While left < right: test pair, move the appropriate pointer.",
                codeExample: "var l = 0, r = nums.count - 1\nwhile l < r { if nums[l] + nums[r] == target { ... }; /* move pointer */ }",
                realWorldExample: "Checking whether two amounts in a sorted ledger sum to a reconciliation target."
            ),
            card(
                name: "Sliding Window",
                suite: "search",
                iconName: "rectangle.leadinghalf.inset.filled",
                tags: ["subarray", "contiguous", "window", "optimization"],
                trigger: "Optimize over a contiguous sub-sequence of a collection.",
                problemShape: "Maximum/minimum subarray, longest substring with constraint, fixed-size window aggregation.",
                desiredResult: "The optimal window in O(n) instead of O(n²) nested loops.",
                mechanism: "Maintain window [left, right]. Expand right on each step; shrink left when invariant is violated.",
                requirements: ["Array or string input", "Window has an invariant that is monotonic as the window grows"],
                advantages: ["O(n) vs O(n²) naive approach", "Constant extra state"],
                costs: ["Window invariant must be maintained precisely; off-by-one errors are common"],
                failureModes: ["Wrong shrink condition; window never shrinks (infinite loop); missing final answer after loop"],
                timeComplexity: "O(n)",
                spaceComplexity: "O(1) to O(k) window state",
                flowDescription: "right expands each step; left advances when invariant breaks. Track best at each valid state.",
                codeExample: "var l = 0, best = 0\nfor r in 0..<s.count { /* add s[r] to window */; while /* violation */ { /* remove s[l]; l += 1 */ }; best = max(best, r - l + 1) }",
                realWorldExample: "Finding the longest run of transactions with no refunds in a payment stream."
            ),
            card(
                name: "Binary Search",
                suite: "search",
                iconName: "divide",
                tags: ["sorted", "logarithmic", "search"],
                trigger: "Find a target in a sorted collection, or the boundary where a property changes.",
                problemShape: "Sorted array; O(log n) lookup required; or finding the leftmost/rightmost valid value.",
                desiredResult: "Index of target, or insertion point / boundary index.",
                mechanism: "Check midpoint; if target < mid, search left half; if target > mid, search right half.",
                requirements: ["Sorted input", "Random access (array-like structure)"],
                advantages: ["O(log n) lookup — 10M elements take ~23 steps"],
                costs: ["Input must be sorted; off-by-one on bounds is a classic bug"],
                failureModes: ["Wrong mid computation causing overflow; incorrect boundary for left-open vs. right-open intervals"],
                timeComplexity: "O(log n)",
                spaceComplexity: "O(1) iterative",
                flowDescription: "lo=0, hi=n. While lo<hi: mid=(lo+hi)/2. Adjust lo or hi based on comparison. Return lo.",
                codeExample: "var lo = 0, hi = arr.count\nwhile lo < hi { let mid = lo + (hi - lo) / 2; if arr[mid] < target { lo = mid + 1 } else { hi = mid } }",
                realWorldExample: "Looking up a rate in a sorted fee schedule by transaction amount threshold."
            )
        ]
    }

    // MARK: Transformation

    private static func transformationCards() -> [KnowledgeCard] {
        [
            card(
                name: "Map",
                suite: "transformation",
                iconName: "arrow.right.circle",
                tags: ["transform", "projection", "functional"],
                trigger: "Transform every element of a collection into a new form.",
                problemShape: "1-to-1 element conversion; same count in, same count out.",
                desiredResult: "New collection of transformed elements.",
                mechanism: "Apply a function to each element; collect results into a new collection.",
                requirements: ["Iterable input", "Pure or side-effect-free transform preferred"],
                advantages: ["Declarative; composable with filter/reduce", "Avoids mutation of the source"],
                costs: ["Allocates a new collection", "Chaining many maps without fusion creates intermediate arrays"],
                failureModes: ["Side effects inside the mapping function; ignoring failed transformations instead of propagating"],
                timeComplexity: "O(n)",
                spaceComplexity: "O(n)",
                flowDescription: "result = [transform(x) for x in input]",
                codeExample: "let names = users.map { $0.displayName }",
                realWorldExample: "Converting raw API response objects to view models for display."
            ),
            card(
                name: "Filter",
                suite: "transformation",
                iconName: "line.3.horizontal.decrease",
                tags: ["predicate", "selection", "functional"],
                trigger: "Remove elements that do not satisfy a condition before downstream processing.",
                problemShape: "Input has noise, invalid records, or irrelevant entries that should not reach later stages.",
                desiredResult: "Subset of the input satisfying the predicate.",
                mechanism: "Apply a boolean predicate to each element; keep elements where it is true.",
                requirements: ["Iterable input"],
                advantages: ["Eliminates noise early; downstream logic stays clean"],
                costs: ["May silently return an empty result if the predicate is wrong", "Allocates a new collection"],
                failureModes: ["Wrong predicate silently discards valid data; filtering without logging drops make debugging hard"],
                timeComplexity: "O(n)",
                spaceComplexity: "O(n) worst case",
                flowDescription: "result = [x for x in input if predicate(x)]",
                codeExample: "let active = users.filter { $0.status == .active }",
                realWorldExample: "Removing test accounts from an analytics query before computing revenue."
            ),
            card(
                name: "Reduce",
                suite: "transformation",
                iconName: "arrow.triangle.merge",
                tags: ["aggregation", "fold", "accumulation", "functional"],
                trigger: "Collapse a collection into a single summary value.",
                problemShape: "Sum, product, concatenation, grouping, or any aggregation over the whole collection.",
                desiredResult: "A single value representing the accumulated result.",
                mechanism: "Start with an initial accumulator; for each element, fold it into the accumulator.",
                requirements: ["Iterable input", "Associative combine operation for correctness"],
                advantages: ["Single pass; flexible — any aggregation fits this shape"],
                costs: ["Non-obvious logic can hide inside the accumulator update", "Order dependency if combine is not commutative"],
                failureModes: ["Wrong initial value; order sensitivity not considered; using reduce for side effects"],
                timeComplexity: "O(n)",
                spaceComplexity: "O(1) for scalar results",
                flowDescription: "acc = initial; for x in input: acc = combine(acc, x); return acc",
                codeExample: "let total = invoices.reduce(0) { $0 + $1.amount }",
                realWorldExample: "Summing invoice amounts grouped by vendor code."
            ),
            card(
                name: "Normalize Data",
                suite: "transformation",
                iconName: "arrow.left.arrow.right.square",
                tags: ["canonicalization", "schema", "cleaning"],
                trigger: "Inconsistent formats arrive from multiple sources before shared processing.",
                problemShape: "Same logical data represented in multiple shapes (date strings, case variants, optional fields).",
                desiredResult: "Canonical internal representation used uniformly downstream.",
                mechanism: "Map all inputs to a single canonical schema before further processing; reject or flag what cannot be normalized.",
                requirements: ["Defined canonical schema", "Knowledge of all source format variations"],
                advantages: ["Isolates format variation at the boundary", "Downstream logic stays clean and format-agnostic"],
                costs: ["Canonical schema must be defined upfront", "Silent truncation of unrecognized fields if not explicit"],
                failureModes: ["Normalizing ambiguous data incorrectly (e.g., MM/DD vs. DD/MM)", "Missing edge cases in source formats"],
                timeComplexity: "O(n)",
                spaceComplexity: "O(n)",
                flowDescription: "parse raw → validate presence of required fields → map to canonical type → reject or flag unknown fields",
                codeExample: "let canonical = raw.map { NormalizedRecord(from: $0) }",
                realWorldExample: "Converting invoice dates from three vendor date formats into UTC ISO-8601 before matching."
            ),
            card(
                name: "Transformation Pipeline",
                suite: "transformation",
                iconName: "arrow.right.circle.fill",
                tags: ["pipeline", "composition", "stages"],
                trigger: "Multiple sequential transformations are needed on a dataset.",
                problemShape: "A series of independent transform steps where each builds on the previous output.",
                desiredResult: "Clean, staged processing where each step can be tested and observed independently.",
                mechanism: "Compose stages; each stage receives the output of the previous. Errors propagate explicitly.",
                requirements: ["Each stage has a well-defined input and output type"],
                advantages: ["Stages are independently testable", "Easy to add, remove, or swap a step"],
                costs: ["Intermediate allocations between stages", "Error in one stage may produce confusing output in later stages if not caught"],
                failureModes: ["Silent bad data passing between stages because no validation exists at stage boundaries"],
                timeComplexity: "O(n · k) where k is number of stages",
                spaceComplexity: "O(n) per stage",
                flowDescription: "input |> stage1 |> stage2 |> ... |> output",
                codeExample: "let result = raw\n  .map(normalize)\n  .filter(isValid)\n  .map(enrich)",
                realWorldExample: "Invoice processing: parse → normalize → validate → enrich with vendor data → match."
            ),
            card(
                name: "Batch Processing",
                suite: "transformation",
                iconName: "square.stack",
                tags: ["throughput", "chunking", "rate-limiting"],
                trigger: "High-volume records are expensive to process individually due to per-call overhead.",
                problemShape: "N items where each individual API call, DB write, or computation has fixed overhead.",
                desiredResult: "Process all items while amortizing overhead across batches.",
                mechanism: "Group records into batches of size B; process each batch atomically; handle partial batches at end.",
                requirements: ["Operation supports batch input", "Batch size tuned to downstream limits"],
                advantages: ["Amortizes per-request overhead", "Respects rate limits naturally"],
                costs: ["Added latency (wait to fill a batch)", "Partial-batch failure handling is more complex than per-item"],
                failureModes: ["Batch too large → OOM or timeout; too small → no throughput gain; failure loses whole batch not just one item"],
                timeComplexity: "O(n)",
                spaceComplexity: "O(batch size)",
                flowDescription: "split(items, size: B) → process each batch → collect results → handle failures per batch",
                codeExample: "for batch in items.chunks(ofCount: 100) { try await api.bulkInsert(Array(batch)) }",
                realWorldExample: "Sending 5,000 notifications in batches of 100 to stay under an API rate limit."
            ),
            card(
                name: "Parse and Validate",
                suite: "transformation",
                iconName: "checkmark.seal",
                tags: ["validation", "parsing", "boundary", "safety"],
                trigger: "Untrusted or externally-sourced data enters the system.",
                problemShape: "Data from user input, file upload, API, or message queue may be malformed, missing fields, or out of range.",
                desiredResult: "A valid, typed internal representation that downstream logic can trust unconditionally.",
                mechanism: "Parse raw bytes/string to a typed structure; then validate invariants (ranges, required fields, cross-field constraints). Reject with a clear error if either step fails.",
                requirements: ["Defined schema", "Clear error path for rejection"],
                advantages: ["Fails fast at the boundary", "Downstream code never handles raw invalid data"],
                costs: ["Every error path must be explicit and handled by callers"],
                failureModes: ["Validation too strict rejects valid edge cases; too loose lets invalid data through silently"],
                timeComplexity: "O(n) input size",
                spaceComplexity: "O(n)",
                flowDescription: "raw bytes → decode to structure → validate fields → return typed value or structured error",
                codeExample: "let order = try JSONDecoder().decode(Order.self, from: data)\nguard order.amount > 0 else { throw ValidationError.negativeAmount }",
                realWorldExample: "Validating a webhook payload from a payment processor before crediting an account."
            )
        ]
    }

    // MARK: Structure

    private static func structureCards() -> [KnowledgeCard] {
        [
            card(
                name: "Extract Function",
                suite: "structure",
                iconName: "square.and.arrow.up",
                tags: ["refactoring", "naming", "testability"],
                trigger: "A code block is reused, too long, or can be described by a single clear name.",
                problemShape: "Long function with multiple responsibilities; duplicated logic; untestable inline code.",
                desiredResult: "Named, focused functions that are independently testable.",
                mechanism: "Move the block to a new function with a descriptive name. Replace original with a call.",
                requirements: ["Identify all variables in and out of the block"],
                advantages: ["Names the intent", "Makes the block unit-testable", "Reduces cognitive load of reading the caller"],
                costs: ["Adds a call frame overhead (negligible in most contexts)", "Risk of premature abstraction for code that is used only once"],
                failureModes: ["Wrong extraction boundary creates hidden coupling", "Function name doesn't match actual behavior"],
                timeComplexity: "O(1) refactor impact",
                spaceComplexity: "O(1)",
                flowDescription: "Identify block → name it → move to function → call from original location → verify behavior unchanged",
                codeExample: "func calculateDiscount(for order: Order) -> Decimal { ... }",
                realWorldExample: "Extracting invoice total calculation from a 200-line order-processing function."
            ),
            card(
                name: "Guard Clause",
                suite: "structure",
                iconName: "shield",
                tags: ["early-return", "precondition", "nesting"],
                trigger: "A function has deeply nested conditionals handling preconditions before the main logic.",
                problemShape: "Happy path is buried under layers of if-else for invalid inputs, missing data, or wrong state.",
                desiredResult: "Main path reads top-to-bottom with minimal nesting.",
                mechanism: "Return early (or throw) at the top of the function for each invalid or uninteresting case.",
                requirements: ["Caller is prepared to handle early returns or thrown errors"],
                advantages: ["Reduces nesting", "Main path logic is easy to follow"],
                costs: ["Multiple return points can surprise readers expecting a single exit", "Must not obscure important logic in the guard"],
                failureModes: ["Guard fires on valid input due to wrong condition", "Too many guards making the entry condition hard to reconstruct"],
                timeComplexity: "O(1)",
                spaceComplexity: "O(1)",
                flowDescription: "guard condition1 else { return/throw }\nguard condition2 else { return/throw }\n// main logic",
                codeExample: "guard let user = session.currentUser else { return .unauthorized }\nguard user.hasPermission(.edit) else { return .forbidden }",
                realWorldExample: "Validating that an invoice exists, is unpaid, and belongs to the current tenant before processing."
            ),
            card(
                name: "Adapter",
                suite: "structure",
                iconName: "arrow.left.arrow.right",
                tags: ["interface", "compatibility", "wrapper"],
                trigger: "Need to use an incompatible interface without modifying either side.",
                problemShape: "Third-party library, legacy code, or external API uses a different interface than your domain expects.",
                desiredResult: "Use the external component via your own interface with no modification to either.",
                mechanism: "Write a wrapper that implements your expected protocol/interface and delegates to the external component.",
                requirements: ["Clear definition of the expected interface"],
                advantages: ["Isolates external API", "Swap implementations by changing only the adapter", "Mockable in tests"],
                costs: ["Extra indirection", "Adapter can leak abstraction if it exposes external-specific types"],
                failureModes: ["Adapter maps incorrectly due to semantic mismatch", "Adapter grows to cover edge cases specific to one implementation"],
                timeComplexity: "O(1) overhead",
                spaceComplexity: "O(1)",
                flowDescription: "Define protocol → implement adapter wrapping external type → inject adapter",
                codeExample: "struct StripeGateway: PaymentGateway {\n  let client: StripeClient\n  func charge(_ amount: Decimal) throws -> Receipt { ... }\n}",
                realWorldExample: "Wrapping three payment processors behind a single PaymentGateway protocol."
            ),
            card(
                name: "Repository",
                suite: "structure",
                iconName: "cylinder.split.1x2",
                tags: ["persistence", "abstraction", "data-access", "testability"],
                trigger: "Persistence logic is scattered through business logic, making testing and switching storage hard.",
                problemShape: "Business objects contain database queries, ORM calls, or file I/O directly.",
                desiredResult: "Business logic queries a clean interface; storage implementation is swappable.",
                mechanism: "Define a protocol with CRUD-style operations. Implement it with the concrete storage. Inject it.",
                requirements: ["Domain model separate from persistence model", "Dependency injection"],
                advantages: ["Business logic is persistence-ignorant", "Storage backend is swappable", "Easily mockable in tests"],
                costs: ["Interface design requires foresight to avoid N+1 or missing query shapes"],
                failureModes: ["Repository becomes a thin ORM wrapper exposing every ORM method — no abstraction gained"],
                timeComplexity: "O(query cost)",
                spaceComplexity: "O(result set)",
                flowDescription: "protocol Repository → implement with storage → inject into service → test with in-memory implementation",
                codeExample: "protocol InvoiceRepository {\n  func find(id: UUID) async throws -> Invoice?\n  func save(_ invoice: Invoice) async throws\n}",
                realWorldExample: "Allowing the same billing service to run against SQLite locally and PostgreSQL in production."
            ),
            card(
                name: "Strategy Pattern",
                suite: "structure",
                iconName: "arrow.branch",
                tags: ["behavior", "interchangeable", "open-closed"],
                trigger: "An algorithm or behavior varies by context but the calling interface stays constant.",
                problemShape: "Switch/if-else selecting from multiple algorithm variants scattered through the codebase.",
                desiredResult: "Caller selects or injects a strategy; adding a new variant requires no change to the caller.",
                mechanism: "Extract each algorithm variant into an object implementing a common protocol. Inject the chosen strategy.",
                requirements: ["Behavior variants share a common input/output contract"],
                advantages: ["Open/closed: add behavior without modifying callers", "Each variant independently testable"],
                costs: ["More protocols/structs; wiring complexity if variants are many"],
                failureModes: ["Strategies with too many tiny differences that actually need the same implementation"],
                timeComplexity: "O(1) dispatch",
                spaceComplexity: "O(1)",
                flowDescription: "protocol Strategy → concrete implementations → inject at call site",
                codeExample: "protocol PricingStrategy { func price(for order: Order) -> Decimal }\nstruct TieredPricing: PricingStrategy { ... }",
                realWorldExample: "Plugging in different discount strategies (seasonal, loyalty, bulk) with the same order pipeline."
            ),
            card(
                name: "Dependency Injection",
                suite: "structure",
                iconName: "arrow.down.to.line",
                tags: ["testability", "coupling", "inversion"],
                trigger: "Testing is hard because dependencies are hidden, global, or constructed internally.",
                problemShape: "Services create their own dependencies; global singletons make isolation impossible.",
                desiredResult: "Dependencies are passed in from outside, making them swappable and mockable.",
                mechanism: "Accept dependencies as constructor parameters or function arguments rather than creating them internally.",
                requirements: ["Callers must provide or wire dependencies"],
                advantages: ["Testable with mock/stub implementations", "Implementation is explicit and auditable"],
                costs: ["More boilerplate at construction sites", "Wiring can become complex in large apps without a container"],
                failureModes: ["DI container misconfigured silently; injecting too many dependencies creating wide interfaces"],
                timeComplexity: "O(1)",
                spaceComplexity: "O(1)",
                flowDescription: "define protocol → pass implementation in init → use protocol internally → inject mock in tests",
                codeExample: "struct PaymentService {\n  let gateway: PaymentGateway\n  init(gateway: PaymentGateway) { self.gateway = gateway }\n}",
                realWorldExample: "Injecting a mock email sender in tests to avoid sending real emails."
            ),
            card(
                name: "Layered Architecture",
                suite: "structure",
                iconName: "square.3.layers.3d",
                tags: ["layers", "separation", "domain", "clean-architecture"],
                trigger: "Business logic is mixed with I/O, UI, or infrastructure code.",
                problemShape: "Changing the database or API format requires editing business rules; domain logic is untestable.",
                desiredResult: "Domain layer is pure and testable; infrastructure is replaceable.",
                mechanism: "Separate code into layers (presentation → application → domain → infrastructure) with dependency rules pointing inward.",
                requirements: ["Discipline to maintain layer boundaries", "Dependency inversion at layer boundaries"],
                advantages: ["Domain is pure and testable without infrastructure", "Layers are replaceable independently"],
                costs: ["Can become ceremonious for simple CRUD applications"],
                failureModes: ["Leaky layer boundaries; anemic domain model where domain has no behavior"],
                timeComplexity: "O(1) overhead per call",
                spaceComplexity: "O(1)",
                flowDescription: "UI → Service/Use-Case → Domain Model → Repository interface → Infrastructure implementation",
                codeExample: "// domain: pure logic\nstruct Invoice { func apply(_ payment: Payment) throws -> Invoice { ... } }\n// infra: implements repo protocol",
                realWorldExample: "Rewriting the database from SQLite to PostgreSQL without touching business rules."
            ),
            card(
                name: "Producer-Consumer",
                suite: "structure",
                iconName: "person.2.wave.2",
                tags: ["queue", "decoupling", "async", "backpressure"],
                trigger: "Work arrives faster than it can be processed, or producers and consumers need to run independently.",
                problemShape: "Tight coupling between ingestion and processing causes back-pressure or resource contention.",
                desiredResult: "Producers enqueue work; consumers dequeue at their own rate; a bounded queue provides backpressure.",
                mechanism: "Producers write to a queue (in-memory channel or durable). Consumers read and process. Queue size caps in-flight work.",
                requirements: ["Queue must be bounded or memory grows unbounded", "Consumer failure must be handled (DLQ or retry)"],
                advantages: ["Decouples ingestion rate from processing rate", "Absorbs traffic bursts"],
                costs: ["Queue adds operational complexity", "Message ordering requires extra design"],
                failureModes: ["Consumer crashes leave queue full; unbounded queue consumes all memory; message loss if queue is not durable"],
                timeComplexity: "O(1) enqueue/dequeue",
                spaceComplexity: "O(queue capacity)",
                flowDescription: "producer → bounded queue → consumer → ack/nack",
                codeExample: "let channel = AsyncStream<Job>.makeStream()\nTask { for await job in channel.stream { await process(job) } }",
                realWorldExample: "Processing incoming webhook events without blocking the HTTP receiver."
            )
        ]
    }

    // MARK: State

    private static func stateCards() -> [KnowledgeCard] {
        [
            card(
                name: "State Machine",
                suite: "state",
                iconName: "circle.hexagongrid.fill",
                tags: ["transitions", "lifecycle", "explicit-states"],
                trigger: "An entity moves through defined states with rules about valid transitions.",
                problemShape: "Boolean flags or ad-hoc conditions scattered across code control allowed operations.",
                desiredResult: "Only valid transitions are possible; illegal states are unrepresentable.",
                mechanism: "Model states as an enum. Transitions are explicit functions that validate the precondition (current state) before moving to the next.",
                requirements: ["Enumerable, bounded set of states", "Clear definition of valid transitions"],
                advantages: ["Illegal states are unrepresentable", "Adding a state requires touching only the state type and explicit transition points"],
                costs: ["Upfront modeling effort", "Rigid when states change frequently"],
                failureModes: ["Silent ignore of invalid transition attempt", "Missing terminal state causes infinite loops"],
                timeComplexity: "O(1) per transition",
                spaceComplexity: "O(states)",
                flowDescription: "current state + event → validate precondition → new state (or error)",
                codeExample: "enum InvoiceState { case draft, submitted, approved, paid, voided }\nfunc submit(_ invoice: inout Invoice) throws {\n  guard invoice.state == .draft else { throw StateError.invalidTransition }\n  invoice.state = .submitted\n}",
                realWorldExample: "An invoice that can be drafted, submitted for approval, approved, paid, or voided."
            ),
            card(
                name: "Immutable State",
                suite: "state",
                iconName: "lock.square",
                tags: ["immutability", "value-types", "thread-safety"],
                trigger: "Shared mutable state causes hard-to-reproduce bugs or race conditions.",
                problemShape: "Multiple references to the same object mutate it unpredictably; snapshots are needed for comparison.",
                desiredResult: "State changes produce new values; old values are unchanged and safe to share.",
                mechanism: "Represent state as value types (struct). Any change returns a new copy with the modification applied.",
                requirements: ["Value semantics in the language (Swift struct, Haskell, etc.)", "Copy-on-write discipline"],
                advantages: ["No aliasing bugs", "Easy to snapshot and diff states", "Thread-safe to read concurrently"],
                costs: ["More allocations", "Deeply nested mutations are verbose without lens-style helpers"],
                failureModes: ["Reference type accidentally embedded in a value type defeats immutability"],
                timeComplexity: "O(1) to O(n) depending on copy size",
                spaceComplexity: "O(n) per version",
                flowDescription: "Read current state → compute new state → replace current with new",
                codeExample: "struct AppState { let count: Int }\nfunc increment(_ state: AppState) -> AppState { AppState(count: state.count + 1) }",
                realWorldExample: "SwiftUI ViewModel using value-type state that triggers a re-render on every change."
            ),
            card(
                name: "Event-Driven Flow",
                suite: "state",
                iconName: "bolt.horizontal",
                tags: ["events", "async", "decoupling", "pub-sub"],
                trigger: "Workflow steps span time, services, or processes and can't run synchronously.",
                problemShape: "Sequential blocking calls chain too many services; one slow step blocks all downstream steps.",
                desiredResult: "Steps emit events; handlers react asynchronously and independently.",
                mechanism: "Each step emits a domain event when it completes. Downstream handlers subscribe and react without the emitter knowing who is listening.",
                requirements: ["Durable event bus or message broker for reliability", "Idempotent handlers"],
                advantages: ["Loose coupling: add subscribers without modifying emitters", "Naturally resilient to partial failure"],
                costs: ["Full flow is harder to trace (need distributed tracing)", "Eventual consistency must be designed for"],
                failureModes: ["Event lost if bus is not durable", "Handler fails silently", "Ordering assumptions violated"],
                timeComplexity: "O(1) to emit",
                spaceComplexity: "O(queue depth)",
                flowDescription: "step completes → emit event → bus routes to subscribers → each subscriber reacts",
                codeExample: "NotificationCenter.default.post(name: .invoiceApproved, object: invoice)",
                realWorldExample: "An invoice approval triggers email notification, accounting entry, and CRM update independently."
            ),
            card(
                name: "Command Pattern",
                suite: "state",
                iconName: "arrow.uturn.backward.square",
                tags: ["undo", "queue", "audit", "encapsulation"],
                trigger: "Operations need to be undone, queued for later, logged, or executed by a different object.",
                problemShape: "Operations are spread as ad-hoc method calls; undo is implemented as a separate code path.",
                desiredResult: "Each operation is an object; undo is its inverse; a history stack enables undo/redo.",
                mechanism: "Encapsulate each operation as a Command with execute() and undo(). Stack executed commands for history.",
                requirements: ["Operations have clear inverse or snapshots for undo"],
                advantages: ["Full operation history", "Supports undo/redo natively", "Schedulable and auditable"],
                costs: ["Every operation needs a command class", "Stale references in command objects"],
                failureModes: ["Undo not fully inverse of execute", "History grows unbounded without a max-depth limit"],
                timeComplexity: "O(1) execute/undo",
                spaceComplexity: "O(history depth)",
                flowDescription: "Create command → execute → push to history. Undo: pop from history → undo.",
                codeExample: "protocol Command { func execute(); func undo() }\nstruct ApplyDiscountCommand: Command { ... }",
                realWorldExample: "A card editor where every change is undoable via Cmd-Z."
            ),
            card(
                name: "Reducer",
                suite: "state",
                iconName: "arrow.3.trianglepath",
                tags: ["redux", "state-management", "pure-function", "predictable"],
                trigger: "UI or domain state is updated from many different event sources and becomes hard to reason about.",
                problemShape: "State mutations scattered across many handlers; hard to trace what caused a particular state.",
                desiredResult: "All state mutations go through a single pure function; state is always computable from action history.",
                mechanism: "Define: reducer(state, action) → newState. All mutations flow through this function. No side effects inside the reducer.",
                requirements: ["Central state representation", "Enumerable actions"],
                advantages: ["Predictable state transitions", "Time-travel debugging", "Easy to test pure functions"],
                costs: ["All state in one place can grow large without slicing", "Side effects (API calls) must live outside the reducer"],
                failureModes: ["Missing action handler returns unchanged state silently", "Reducer has side effects that cause non-determinism"],
                timeComplexity: "O(1) per action",
                spaceComplexity: "O(state size)",
                flowDescription: "dispatch(action) → reducer(currentState, action) → newState → update store",
                codeExample: "func reduce(_ state: AppState, _ action: Action) -> AppState {\n  switch action {\n  case .addCard(let c): return AppState(cards: state.cards + [c])\n  }\n}",
                realWorldExample: "Managing a complex multi-step form where each field change triggers validation and dependent field updates."
            ),
            card(
                name: "Finite Workflow States",
                suite: "state",
                iconName: "list.bullet.rectangle",
                tags: ["workflow", "lifecycle", "business-process"],
                trigger: "A business entity moves through a documented lifecycle with named stages.",
                problemShape: "Status is a free-form string or a pile of boolean flags; valid next steps are not enforced.",
                desiredResult: "Each stage is named; transitions are explicit domain events; invalid stages are impossible.",
                mechanism: "Model the workflow as a sealed set of states. Each transition is a named domain operation that validates preconditions.",
                requirements: ["Stakeholder-agreed stage names", "Well-defined entry/exit conditions per stage"],
                advantages: ["Contract is clear for all engineers and domain experts", "Invalid intermediate states are impossible"],
                costs: ["Changes to the workflow require schema migration for persisted state"],
                failureModes: ["State explosion from mixing unrelated flags", "Missing terminal state causes orphaned records"],
                timeComplexity: "O(1) per transition",
                spaceComplexity: "O(1)",
                flowDescription: "Define all stages as enum cases → map transitions as domain events → persist current stage",
                codeExample: "enum ClaimStatus { case submitted, underReview, approved, rejected, paid }",
                realWorldExample: "An insurance claim moving through submitted → under review → approved → paid."
            )
        ]
    }

    // MARK: Reliability

    private static func reliabilityCards() -> [KnowledgeCard] {
        [
            card(
                name: "Input Validation",
                suite: "reliability",
                iconName: "checkmark.circle",
                tags: ["safety", "boundary", "defensive"],
                trigger: "Data arrives from user input, external API, file, or message queue.",
                problemShape: "Downstream code assumes valid data but receives malformed, out-of-range, or missing values.",
                desiredResult: "System rejects or sanitizes invalid data at the boundary; internals never process known-bad input.",
                mechanism: "Check types, ranges, required fields, and cross-field constraints at the entry point. Return structured errors on failure.",
                requirements: ["Defined valid range and shape for all inputs"],
                advantages: ["Fails fast with a clear error", "Downstream code can trust its inputs"],
                costs: ["Must anticipate all invalid forms; hard to be exhaustive"],
                failureModes: ["Validation too lenient (missing edge cases); validation so strict it rejects valid inputs"],
                timeComplexity: "O(n) input size",
                spaceComplexity: "O(1)",
                flowDescription: "receive → check type → check range → check required → check cross-field → accept or reject",
                codeExample: "guard amount > 0, amount <= 1_000_000 else { throw ValidationError.amountOutOfRange }",
                realWorldExample: "Rejecting a payment request with a negative or zero amount before it reaches the payment gateway."
            ),
            card(
                name: "Idempotency",
                suite: "reliability",
                iconName: "repeat",
                tags: ["safety", "retry", "deduplication", "at-least-once"],
                trigger: "An operation may be retried due to network failure or at-least-once message delivery.",
                problemShape: "Duplicate execution of a non-idempotent operation causes double charges, duplicate records, or conflicting state.",
                desiredResult: "Executing the operation multiple times with the same input has the same effect as executing it once.",
                mechanism: "Assign a unique request ID (client-generated or derived from content). Before executing, check if this ID was already processed. Return cached result if so.",
                requirements: ["Stable unique key per logical operation", "Storage for processed key set"],
                advantages: ["Safe to retry without fear of duplicate effects"],
                costs: ["Dedup key storage grows; keys must be cleaned up eventually"],
                failureModes: ["Dedup key expires before client retries", "Side effects outside the idempotency scope still execute twice"],
                timeComplexity: "O(1) lookup",
                spaceComplexity: "O(distinct keys)",
                flowDescription: "receive request with key → lookup key in store → if found return cached result → else process and store result with key",
                codeExample: "guard !processedIDs.contains(requestID) else { return cachedResult(for: requestID) }\nlet result = try await process(request)\nprocessedIDs.insert(requestID)\nreturn result",
                realWorldExample: "Preventing a webhook from charging a customer twice when the payment processor retries delivery."
            ),
            card(
                name: "Retry with Backoff",
                suite: "reliability",
                iconName: "arrow.counterclockwise",
                tags: ["resilience", "transient-failure", "exponential-backoff"],
                trigger: "A call to an external service fails due to transient network errors, rate limits, or temporary unavailability.",
                problemShape: "Transient failures cause false negatives; immediate retry floods the service; no retry loses the operation.",
                desiredResult: "Automatically recover from transient failures with safe inter-attempt delays.",
                mechanism: "Catch retriable error types. Wait an exponentially increasing delay (plus random jitter) between attempts. Stop after max attempts.",
                requirements: ["Clear definition of retriable vs. non-retriable errors", "Max retry count and backoff cap"],
                advantages: ["Recovers from transient failures automatically without caller involvement"],
                costs: ["Adds latency proportional to backoff delay", "Amplifies load during outages if too aggressive"],
                failureModes: ["Retrying non-retriable errors (e.g., 400 Bad Request)", "No max retry or cap causes infinite loops", "No jitter causes thundering herd"],
                timeComplexity: "O(retries · backoff)",
                spaceComplexity: "O(1)",
                flowDescription: "attempt → on retriable error: wait(base * 2^attempt + jitter) → retry up to max → propagate on final failure",
                codeExample: "for attempt in 0..<maxRetries {\n  do { return try await call() }\n  catch where isRetriable(error) {\n    let delay = baseDelay * pow(2, Double(attempt)) + .random(in: 0...0.1)\n    try await Task.sleep(for: .seconds(delay))\n  }\n}",
                realWorldExample: "Retrying a failed call to a payment gateway during a 30-second service disruption."
            ),
            card(
                name: "Circuit Breaker",
                suite: "reliability",
                iconName: "switch.2",
                tags: ["resilience", "failure-isolation", "cascade-prevention"],
                trigger: "A downstream service is failing and retries are amplifying the load, making recovery harder.",
                problemShape: "Every request waits for timeout; failures cascade; the failing service never gets breathing room to recover.",
                desiredResult: "After a failure threshold is crossed, stop sending requests. Resume gradually after a cooldown.",
                mechanism: "Three states: Closed (normal), Open (failing — reject immediately), Half-Open (probe). Count failures; open after threshold; probe after cooldown; close on success.",
                requirements: ["Failure threshold and cooldown duration tuned to the dependency", "Fallback behavior in Open state"],
                advantages: ["Stops cascade failures", "Gives downstream service time to recover"],
                costs: ["Extra state machine", "Requires tuning thresholds for each dependency"],
                failureModes: ["Threshold too sensitive (opens on single blip)", "Circuit never closes if probe keeps failing", "Shared circuit across unrelated operations"],
                timeComplexity: "O(1)",
                spaceComplexity: "O(1)",
                flowDescription: "request → check state → Closed: call + count failures → Open: return fallback immediately → Half-Open: probe",
                codeExample: "if breaker.state == .open { return .serviceUnavailable }\ndo { let r = try await call(); breaker.recordSuccess(); return r }\ncatch { breaker.recordFailure(); throw error }",
                realWorldExample: "Stopping calls to a credit bureau API during a known outage, returning cached scores instead."
            ),
            card(
                name: "Queue",
                suite: "reliability",
                iconName: "tray.full",
                tags: ["durability", "decoupling", "async", "backpressure"],
                trigger: "Work must survive process restarts, or producers and consumers must run at different rates.",
                problemShape: "Synchronous processing loses work on crash; tight coupling of producer and consumer blocks both.",
                desiredResult: "Work items are persisted until successfully processed; producer never blocks on consumer.",
                mechanism: "Persist work items in a durable queue. Consumer reads, processes, then acknowledges (ack). Unacked items are redelivered after timeout.",
                requirements: ["Durable storage for the queue", "Consumer acknowledges only after successful processing"],
                advantages: ["Survives crashes (durable queue)", "Smooths traffic spikes", "Producer/consumer are independently scalable"],
                costs: ["Operational overhead", "Message ordering requires extra design", "At-least-once delivery requires idempotent consumers"],
                failureModes: ["Consumer never acks → redelivery loop", "Queue grows unbounded if consumer is too slow", "Non-durable queue loses messages on restart"],
                timeComplexity: "O(1) enqueue/dequeue",
                spaceComplexity: "O(queue depth)",
                flowDescription: "producer → enqueue → queue stores durably → consumer dequeues → processes → acks",
                codeExample: "try await queue.send(ProcessInvoiceJob(invoiceID: id))",
                realWorldExample: "Queuing invoice processing jobs so none are lost if the server restarts mid-batch."
            ),
            card(
                name: "Dead-Letter Handling",
                suite: "reliability",
                iconName: "exclamationmark.triangle",
                tags: ["error-handling", "queue", "poison-message", "recovery"],
                trigger: "Some messages repeatedly fail processing and block the queue.",
                problemShape: "A poison message fails every time, causing retries that block later messages and consume retry budget.",
                desiredResult: "Failing messages are isolated without losing them, so the queue can continue processing healthy messages.",
                mechanism: "After max retries, route the message to a dead-letter queue (DLQ). Alert operators. Provide tooling to inspect, fix, and replay DLQ messages.",
                requirements: ["DLQ storage", "Monitoring on DLQ depth", "Replay mechanism"],
                advantages: ["No message loss", "Poison messages don't block healthy processing"],
                costs: ["DLQ must be monitored; messages accumulate if ignored", "Manual remediation is required"],
                failureModes: ["DLQ never monitored — bad messages accumulate forever", "Replay replays without fixing the root cause"],
                timeComplexity: "O(1) route to DLQ",
                spaceComplexity: "O(failed messages)",
                flowDescription: "process → fail → retry N times → move to DLQ → alert → human review → fix → replay",
                codeExample: "if attempts >= maxRetries { try await deadLetterQueue.send(message); return }",
                realWorldExample: "Routing malformed invoice XML to a DLQ so an engineer can correct and reprocess it."
            ),
            card(
                name: "Audit Trail",
                suite: "reliability",
                iconName: "doc.text.magnifyingglass",
                tags: ["logging", "history", "compliance", "forensics"],
                trigger: "Need to know who did what and when, or recover from corrupted state.",
                problemShape: "A bug or user action caused bad state but there is no record of what happened or in what order.",
                desiredResult: "Append-only log of all state-changing events with timestamp, actor, and before/after values.",
                mechanism: "On every mutation, append an audit entry to an immutable log. Never update or delete audit records.",
                requirements: ["Append-only storage", "Audit entries linked to the mutated entity"],
                advantages: ["Full history for investigation and replay", "Supports compliance and dispute resolution"],
                costs: ["Storage grows without bound; must be pruned or archived eventually", "Must not be bypassed by any code path"],
                failureModes: ["Audit skipped for some code paths (incomplete coverage)", "Audit entries not tamper-evident"],
                timeComplexity: "O(1) write",
                spaceComplexity: "O(events over time)",
                flowDescription: "before mutation → write audit entry → apply mutation → confirm",
                codeExample: "auditLog.append(AuditEntry(actor: user.id, action: .approve, entityID: invoice.id, at: .now))",
                realWorldExample: "Recording every approval and rejection of an expense report for compliance review."
            ),
            card(
                name: "Timeout",
                suite: "reliability",
                iconName: "timer",
                tags: ["resilience", "latency", "resource-management"],
                trigger: "An external call may hang indefinitely, blocking a thread or task.",
                problemShape: "A slow dependency causes the caller to wait forever, exhausting connection pools or task budgets.",
                desiredResult: "All external calls complete (success or error) within a bounded time.",
                mechanism: "Set a deadline on every external call. If the deadline is exceeded, cancel the call and surface a timeout error.",
                requirements: ["Async cancellation supported by the underlying API"],
                advantages: ["Prevents resource exhaustion from hanging calls", "Surfaces slow dependencies explicitly"],
                costs: ["Timeout too short causes false failures; too long wastes resources during outages"],
                failureModes: ["Timeout not propagated through all layers", "Partial work performed before timeout is not rolled back"],
                timeComplexity: "O(1)",
                spaceComplexity: "O(1)",
                flowDescription: "start call → start timer → if timer fires before response: cancel + return timeout error",
                codeExample: "try await withTimeout(.seconds(5)) { try await externalAPI.fetchVendor(id) }",
                realWorldExample: "Capping a vendor lookup to 3 seconds so a slow vendor database doesn't delay invoice processing."
            ),
            card(
                name: "Graceful Degradation",
                suite: "reliability",
                iconName: "arrow.down.right.circle",
                tags: ["resilience", "fallback", "partial-availability"],
                trigger: "A non-critical dependency is unavailable and the system should keep running in reduced form.",
                problemShape: "Full unavailability when one optional component fails; all-or-nothing error handling.",
                desiredResult: "Core functionality remains available; reduced but correct behavior is served during partial outages.",
                mechanism: "Detect dependency failure. Serve reduced functionality (cached data, defaults, skip optional enrichment) without crashing the main flow.",
                requirements: ["Explicitly designed degraded path", "Degraded behavior tested independently"],
                advantages: ["System stays partially useful during partial outages"],
                costs: ["Degraded path must be designed and tested; can hide a broken dependency if not alarmed"],
                failureModes: ["Degraded path untested in production conditions", "Silent data loss in degraded mode not surfaced to users"],
                timeComplexity: "O(1) detection",
                spaceComplexity: "O(1)",
                flowDescription: "call dependency → on failure: log + return cached/default → continue with reduced result",
                codeExample: "let enriched = (try? await vendorAPI.fetch(id)) ?? cachedVendor(id)",
                realWorldExample: "Showing invoices from local cache when the vendor enrichment service is down."
            )
        ]
    }

    // MARK: Debugging

    private static func debuggingCards() -> [KnowledgeCard] {
        [
            card(
                name: "Reproduce",
                suite: "debugging",
                iconName: "arrow.clockwise",
                tags: ["reproduction", "steps", "environment"],
                trigger: "A bug report exists with no reliable reproduction steps.",
                problemShape: "Bug is described by symptoms, not by steps. May be environment- or data-specific.",
                desiredResult: "A sequence of steps that triggers the bug reliably in a controlled environment.",
                mechanism: "Gather exact inputs, environment version, OS, data state, and sequence of user actions from the reporter. Replay in isolation. Iterate until the bug is triggered consistently.",
                requirements: ["Access to the same or equivalent environment", "All relevant configuration and data"],
                advantages: ["A reproducible bug is half fixed", "The reproduction becomes the regression test"],
                costs: ["Time-consuming", "Environment differences make some bugs irreproducible outside production"],
                failureModes: ["Heisenbug: observation changes behavior", "Mismatch between reporter's environment and debug environment"],
                timeComplexity: "O(investigation time)",
                spaceComplexity: "O(1)",
                flowDescription: "gather report → identify environment and data → replicate environment → replay steps → confirm trigger",
                codeExample: "// Test: given invoice.status == .approved and user.role == .viewer, calling approve() should throw .unauthorized",
                realWorldExample: "Reproducing a double-charge that only occurs when a user double-clicks the submit button within 200ms."
            ),
            card(
                name: "Reduce to Minimal Case",
                suite: "debugging",
                iconName: "minus.magnifyingglass",
                tags: ["isolation", "minimal", "simplification"],
                trigger: "The bug is buried in complex real-world data or a large codebase.",
                problemShape: "Reproduction exists but involves too much code and data to reason about.",
                desiredResult: "Smallest possible input and code path that still triggers the bug.",
                mechanism: "Strip away everything not required to trigger the bug. Test after each removal. Stop only when removing more breaks the reproduction.",
                requirements: ["Working reproduction to start from"],
                advantages: ["Isolates the root cause clearly", "Minimal case becomes the regression test"],
                costs: ["Reduction is slow for large systems", "Wrong stopping point yields a case that doesn't reproduce the real bug"],
                failureModes: ["Stop too early", "Reduced case shares symptom but has a different root cause from the original"],
                timeComplexity: "O(n) reductions",
                spaceComplexity: "O(minimal case size)",
                flowDescription: "start with full reproduction → remove components → test each removal → stop when removal breaks reproduction",
                codeExample: "// Stripped to: let result = match(amount: 100.0, vendorID: \"X\") — fails\n// All other fields and context removed",
                realWorldExample: "Narrowing a 2,000-line test fixture to the three invoice fields that actually trigger the matching bug."
            ),
            card(
                name: "Trace the Data",
                suite: "debugging",
                iconName: "arrow.forward.square",
                tags: ["logging", "data-flow", "inspection"],
                trigger: "Output is wrong but the cause is unclear because the data passes through multiple stages.",
                problemShape: "A value enters correct and exits wrong, but the transformation is opaque.",
                desiredResult: "Identify the exact stage where the data first diverges from the expected value.",
                mechanism: "Log or inspect the data value at each transformation step. Compare to expected at each point. The first divergence is the bug site.",
                requirements: ["Ability to add instrumentation to each stage"],
                advantages: ["Precisely pinpoints the stage that introduces the error"],
                costs: ["Requires adding instrumentation", "Log volume is noisy in production"],
                failureModes: ["The logged path is not the actual execution path", "Aliasing hides mutations in a different reference"],
                timeComplexity: "O(pipeline depth)",
                spaceComplexity: "O(log volume)",
                flowDescription: "add log at each stage → run → compare expected vs. actual at each log point → first divergence = bug site",
                codeExample: "print(\"[trace] after normalize:\", record)\nprint(\"[trace] after match:\", result)",
                realWorldExample: "Logging the invoice amount at each enrichment step to find where it becomes zero."
            ),
            card(
                name: "Compare Expected vs. Actual",
                suite: "debugging",
                iconName: "arrow.left.arrow.right.square",
                tags: ["comparison", "diff", "specification"],
                trigger: "Output differs from the specification or previous correct behavior.",
                problemShape: "Something is wrong but the wrong thing hasn't been precisely identified.",
                desiredResult: "A concrete, explicit diff between the expected and actual output that reveals the discrepancy.",
                mechanism: "Write down the expected output explicitly. Capture the actual output. Diff them systematically, field by field.",
                requirements: ["Knowledge of what the correct output should be"],
                advantages: ["Makes the discrepancy concrete and precise", "Often reveals assumption errors about what 'correct' means"],
                costs: ["Requires knowing the expected value — which may itself be wrong"],
                failureModes: ["Expected value is wrong", "Diff is too large to read without a structured comparison tool"],
                timeComplexity: "O(output size)",
                spaceComplexity: "O(output)",
                flowDescription: "specify expected → run → capture actual → diff → focus on first difference",
                codeExample: "XCTAssertEqual(actual.amount, expected.amount)\nXCTAssertEqual(actual.vendorID, expected.vendorID)",
                realWorldExample: "Diffing the generated invoice PDF field by field against the approved spec to find the wrong tax rate."
            ),
            card(
                name: "Check Invariants",
                suite: "debugging",
                iconName: "checkmark.shield",
                tags: ["assertions", "consistency", "invariants"],
                trigger: "State corruption or inconsistency is detected but the source is unknown.",
                problemShape: "The system is in a bad state but no single operation is obviously wrong.",
                desiredResult: "Determine where an invariant was first violated, narrowing the search space.",
                mechanism: "Define invariants (conditions that must always be true) and encode them as assertions. Run the checker over current state and at every system boundary.",
                requirements: ["Invariants must be explicitly defined and encoded"],
                advantages: ["Narrows the search to where the invariant first breaks", "Assertions catch violations early in tests"],
                costs: ["Invariants themselves can be wrong", "Checking at every boundary has performance cost in production"],
                failureModes: ["Invariant checker has a bug", "Invariant is too weak to catch the actual violation"],
                timeComplexity: "O(state size)",
                spaceComplexity: "O(1)",
                flowDescription: "define invariants → add assertions → run over state → find first violated assertion → that's the bug site",
                codeExample: "assert(invoice.amount >= 0, \"Invoice amount must be non-negative\")\nassert(invoice.lineItems.map(\\.amount).reduce(0, +) == invoice.amount, \"Line items must sum to total\")",
                realWorldExample: "Adding an assertion that invoice line items always sum to the invoice total to catch a rounding bug."
            ),
            card(
                name: "Binary-Search Debugging",
                suite: "debugging",
                iconName: "arrow.up.and.down.and.arrow.left.and.right",
                tags: ["git-bisect", "narrowing", "commits", "log-n"],
                trigger: "A bug exists somewhere in a large range: commits, data records, config values, or code.",
                problemShape: "Too many candidates to check individually; the regression is somewhere in a large range.",
                desiredResult: "Identify the exact commit, record, or configuration that introduced or triggers the bug.",
                mechanism: "Test the midpoint of the range. If the bug is present, it's in the first half. If absent, it's in the second half. Repeat.",
                requirements: ["A test that reliably identifies 'bug present' vs. 'bug absent'", "Monotonic property in the range (bug introduced once, not oscillating)"],
                advantages: ["O(log n) through commit history or config space"],
                costs: ["Each step requires building and running a full test"],
                failureModes: ["Bug is non-monotonic (appears only in a window, not a half)", "Test is flaky making the bisect unreliable"],
                timeComplexity: "O(log n) steps",
                spaceComplexity: "O(1)",
                flowDescription: "lo = known-good, hi = known-bad. mid = (lo+hi)/2. Test mid. If bad: hi = mid. If good: lo = mid. Repeat.",
                codeExample: "# git bisect start\n# git bisect bad HEAD\n# git bisect good v1.2.0\n# git bisect run ./test.sh",
                realWorldExample: "Using git bisect to find the commit that introduced a 10% regression in invoice match rate."
            ),
            card(
                name: "Add Observability",
                suite: "debugging",
                iconName: "eye",
                tags: ["metrics", "logging", "tracing", "visibility"],
                trigger: "A recurring issue in production has no visibility into internal state.",
                problemShape: "Something goes wrong intermittently but there are no logs, metrics, or traces to diagnose it.",
                desiredResult: "Internal state at the time of the failure is captured and queryable.",
                mechanism: "Add structured logging, metrics counters, and distributed traces at key decision points. Deploy and observe the next occurrence.",
                requirements: ["Log aggregation system", "Metrics pipeline", "Defined what to measure"],
                advantages: ["Enables root cause analysis without needing to reproduce the bug"],
                costs: ["Log volume and storage cost", "Sensitive data in logs is a compliance risk"],
                failureModes: ["Wrong granularity (too coarse to be useful; too fine to query)", "Cardinality explosion in metric labels", "Logs exist but are not queryable"],
                timeComplexity: "O(1) per event emitted",
                spaceComplexity: "O(log volume)",
                flowDescription: "identify key decision points → add structured logs/metrics/spans → deploy → observe on next occurrence",
                codeExample: "logger.info(\"match_attempt\", metadata: [\"invoiceID\": .string(id), \"vendor\": .string(v), \"result\": .string(r)])",
                realWorldExample: "Adding a log line for every invoice match attempt so the failure pattern becomes visible in Datadog."
            ),
            card(
                name: "Dependency Isolation",
                suite: "debugging",
                iconName: "arrow.up.left.and.arrow.down.right",
                tags: ["isolation", "stub", "attribution"],
                trigger: "Not sure whether the bug is in your code or a dependency.",
                problemShape: "A failure occurs at the boundary with a library, service, or external system.",
                desiredResult: "Confirm or rule out the dependency as the cause of the bug.",
                mechanism: "Replace the dependency with the simplest possible stub or hardcoded response. Run the test. If the bug disappears, the dependency is the cause. If it remains, the bug is in your code.",
                requirements: ["Ability to inject or replace the dependency"],
                advantages: ["Definitively attributes the bug to your code or the dependency"],
                costs: ["Stub may not faithfully replicate all behavior of the dependency"],
                failureModes: ["Stub too simple — doesn't reproduce the specific behavior that triggers the bug", "Integration behavior differs from isolated behavior"],
                timeComplexity: "O(isolation setup)",
                spaceComplexity: "O(1)",
                flowDescription: "identify suspect dependency → stub it → run test → if bug gone: dependency is cause → if bug remains: bug is yours",
                codeExample: "let stub = MockPaymentGateway(response: .success(amount: 100))\nlet service = PaymentService(gateway: stub)\ntry await service.charge(order)",
                realWorldExample: "Stubbing the vendor API with a hardcoded response to confirm the matching bug is in the local logic, not the API data."
            )
        ]
    }
}
